version: '3'
services:
    mongodb:
        image: mongo
        container_name: {{ cookiecutter.project_slug }}-mongodb
        volumes:
            - ../deployment/{{ cookiecutter.project_slug }}/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
 
    web:
        build: .
        image: {{ cookiecutter.project_slug }}-image
        container_name: {{ cookiecutter.project_slug }}-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9000:9000
        links:
            - mongodb
        networks:
            - default
        restart: always
        environment:
            {{ cookiecutter.project_slug.upper() }}_SETTINGS: /app/{{ cookiecutter.project_slug }}-production.cfg
        command:
            uwsgi --lazy-apps --ini scripts/{{ cookiecutter.project_slug }}-uwsgi.ini
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    

networks:
    default:
